# Application Properties
spring.application.name=book-store

# Server port
server.port=8081

######################################
# Datasource Configuration
######################################
spring.datasource.url=jdbc:postgresql://localhost:5432/bookshop_db
# application-docker.properties (for Docker or tests)
#spring.datasource.url=jdbc:postgresql://postgres:5432/bookshop_db
spring.datasource.username=postgres
spring.datasource.password=ShivaniDeviyani@2025
spring.datasource.driver-class-name=org.postgresql.Driver

# For Docker backend (inside container)
# application-docker.properties
# spring.datasource.url=jdbc:postgresql://postgres:5432/bookshop_db

# Static resources location
spring.web.resources.static-locations=file:uploads/

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.devtools.restart.exclude=hibernate-types-60-*.jar

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=uploads

# Logging
#logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.messaging.simp=INFO
logging.level.org.springframework.web.socket=INFO

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework=DEBUG
logging.level.com.itc.book_store=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always

# allow up to 50 parts in a single multipart request
server.tomcat.max-part-count=50

# (optional) also tune other related limits
server.tomcat.max-swallow-size=-1
server.tomcat.max-parameter-count=1000


#aws.s3.bucketName=book-store-app-bucket-parth
#aws.s3.accessKey=AKIAQPVSCYWK52PZKLW2
#aws.s3.secretKey=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
#aws.s3.region=eu-north-1

aws.s3.bucketName=myappbookshop
aws.s3.accessKey=AKIAZCZXXKANE5WOJMOF
aws.s3.secretKey=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
aws.s3.region=eu-north-1


jwt.private-key-path=classpath:keys/private_key.pem
jwt.public-key-path=classpath:keys/public_key.pem
jwt.expiration-ms=3600000

    # =============================
    # Payments / Stripe Configuration
    # =============================
app.payments.stripe.api-key=${STRIPE_SECRET_KEY}
app.payments.stripe.account=${STRIPE_ACCOUNT:}
app.payments.webhook-secret=${STRIPE_WEBHOOK_SECRET}
app.payments.stripe.frontend-origin=${FRONTEND_ORIGIN:http://localhost:3000}

####################################
# Kafka Configuration (Localhost)
####################################

#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=localhost:9092
# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=3
spring.kafka.producer.linger-ms=5

# Consumer
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest

# Wrap deserializers with ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON settings
spring.kafka.consumer.properties.spring.json.trusted.packages=com.itc.book_store.dto.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=com.itc.book_store.dto.kafka.OrderNotification


# Auto commit (fine for dev)
spring.kafka.consumer.enable-auto-commit=true

# Topics
app.kafka.topic.orders=om_kafka_order
app.kafka.topic.order-status=order_status_updated







